<a href="https://colab.research.google.com/github/YoussefDiaa1/Ai-ripo/blob/main/Python_Numpy_Exercises_with_hints_50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [1]:
import numpy as np
np.__version__
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [2]:
list = [1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [3]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [4]:
x = np.zeros((10,10))
print("%d bytes" % (x.size * x.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [6]:
Z = np.zeros(12)
Z[5] = 1
print(Z)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [7]:
Z = np.arange(20, 60)
print(Z)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [9]:
Z = np.arange(12, 21).reshape(3, 3)
print(Z)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [10]:
Z = np.array([3,7,0,0,9,0])
print(np.nonzero(Z))

(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [11]:
Z = np.eye(4)
print(Z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [12]:
Z = np.random.random((2,2,2))
print(Z)

[[[0.10677532 0.18997988]
  [0.52090259 0.00319839]]

 [[0.09926095 0.50140413]
  [0.93584145 0.22732851]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [13]:
Z = np.random.random((9,9))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0017981076337669766 0.9921122249712266


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [14]:
Z = np.random.random(20)
print(Z.mean())

0.49354696896393857


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [18]:
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [19]:
Z = np.zeros((6,6),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [20]:
Z = np.arange(8*9*10).reshape(8,9,10)
print(np.unravel_index(99, Z.shape))

(np.int64(1), np.int64(0), np.int64(9))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [21]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [22]:
Z = np.random.random((6,6))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[ 0.24710187 -0.06721591  1.03878681  1.84098997  1.42513905 -0.64100184]
 [ 0.33283915 -1.28292454 -0.95811786 -0.20912822  1.22989786  0.48858785]
 [ 0.25775529 -1.01117649 -0.47471304 -1.31161279  0.18179813 -0.85515422]
 [-1.31732001 -0.69243195  1.65178268  0.70523968  1.60600329 -1.24767524]
 [ 0.9745909  -0.9910712  -0.54677256 -1.24430966  1.83824026  1.03669164]
 [ 0.26741116 -0.80679151 -1.11888496  0.67153231 -0.54299599 -0.4750899 ]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [23]:
Z = np.random.random((5,5))
print("Number of elements:", Z.size)
print("Length of one array element in bytes:", Z.itemsize)
print("Total bytes consumed by the elements:", Z.nbytes)

Number of elements: 25
Length of one array element in bytes: 8
Total bytes consumed by the elements: 200


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [24]:
Z = np.dot(np.ones((6,3)), np.ones((3,4)))
print(Z)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [25]:
Z = np.arange(10)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [27]:
a = np.array([1, 2])
b = np.array([4, 5])
print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
a = np.arange(5)
print(a**a)
print(a << a >> 2)
print(a < -a)
print(1j*a)
print(a/1/1)
# print(aa) # This will cause an error as 'aa' is not defined.

nan
0
[-9.22337204e+18]
[  1   1   4  27 256]
[ 0  0  2  6 16]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


/tmp/ipython-input-4154046307.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-4154046307.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-4154046307.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [29]:
Z = np.random.uniform(-10, 10, 10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 2.29246783  4.53703181  1.27752717 -2.71573293 -9.99431712 -8.27805556
  6.17230753 -9.57237744  5.82720738  4.86795299]
[  3.   5.   2.  -3. -10.  -9.   7. -10.   6.   5.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

In [32]:
# This is not recommended, but can be done using np.seterr or np.errstate
#Example with np.seterr:
oldsettings = np.seterr(all='ignore')
print(np.array(0) / np.array(0))
np.seterr(**oldsettings)  # Restore old settings

# Example with np.errstate:
with np.errstate(all='ignore'):
   print(np.array(0) / np.array(0))

# Since ignoring warnings is not recommended, I will just add a comment explaining how.
#print("Ignoring numpy warnings is not recommended.")
#print("Use np.seterr(all='ignore') or np.errstate(all='ignore') with a 'with' block.")

nan
nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipython-input-2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

In [34]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print('Yesterday:', yesterday)
print('Today:', today)
print('Tomorrow:', tomorrow)

Yesterday: 2025-08-11
Today: 2025-08-12
Tomorrow: 2025-08-13


#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

In [35]:
Z = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print(Z)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [36]:
A = np.ones(10)
B = np.ones(10)
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)
print(A)

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

In [37]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1) # Method 1: Using modulo
print(np.floor(Z)) # Method 2: Using np.floor
print(Z.astype(int)) # Method 3: Using astype
print(np.trunc(Z)) # Method 4: Using np.trunc

[6.30584784 3.27651043 4.81000115 9.70105469 2.05809407 7.92141315
 8.9280196  0.38792865 6.05550087 9.28295713]
[6. 3. 4. 9. 2. 7. 8. 0. 6. 9.]
[6. 3. 4. 9. 2. 7. 8. 0. 6. 9.]
[6 3 4 9 2 7 8 0 6 9]
[6. 3. 4. 9. 2. 7. 8. 0. 6. 9.]


#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

In [38]:
Z = np.zeros((3,3))
Z[:,:] = np.arange(3)
print(Z)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

In [39]:
def generate_integers():
  for i in range(9):
    yield i

Z = np.fromiter(generate_integers(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

In [40]:
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

In [41]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14323434 0.18084466 0.28599791 0.32734542 0.39557472 0.39936193
 0.72932425 0.75844454 0.78049023 0.93188966]


#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

In [42]:
Z = np.arange(10)
# For small arrays, np.add.reduce can be faster than np.sum
print(np.add.reduce(Z))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

In [43]:
A = np.random.rand(5)
B = np.random.rand(5)
print(np.allclose(A, B))
print(np.array_equal(A, B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

In [45]:
Z = np.zeros(10)
Z.flags.writeable = False
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

In [46]:
Z = np.random.random((5,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.05989464 0.82451292 0.95250799 0.75216107 0.46174455]
[0.89416886 0.01898453 0.35451296 1.17768782 0.84300159]


#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

In [47]:
Z = np.random.random(5)
Z[Z.argmax()] = 0
print(Z)

[0.91384213 0.         0.05506439 0.77626959 0.54360052]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

In [53]:
np.set_printoptions(threshold=np.inf)

Z = np.arange(100)
print(Z)

np.set_printoptions(threshold=1000) # Reset to default

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

In [52]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

47


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`

# Task
Solve all the exercises in the provided notebook.

## Solve exercise 6

### Subtask:
Create a null vector of size 12 but the sixth value which is 1.


**Reasoning**:
The subtask requires creating a null vector of size 12 and setting the sixth element to 1. This can be achieved using `np.zeros()` to create the null vector and then indexing to set the value of the sixth element.

